### ISSUE TITLE
'\w' gets transpiled to 'w'

### ISSUE THREAD

**Issue by NoNoNo** [mrcoles/bookmarklet#10]
Source: 

```js
console.log('\w');
```

Expected result:

```js
console.log('\w');
```
Actual result:

```js
console.log('w');
```

Thanks & greetings!

**Comment by mrcoles** [comment]
Hey @NoNoNo I think '\w' and 'w' are the same things in javascript?

For example, take a look at this:

![Screen Shot 2019-09-09 at 1 17 58 PM](https://user-images.githubusercontent.com/136651/64551986-4e63bd00-d304-11e9-9572-d4ae68c9b2c7.png)

**Comment by NoNoNo** [comment]
thanks @mrcoles! It was a oversimplified test case.

I used to construct a regex with `new RegExp()` like

```js
console.log(new RegExp('\w'));
```

So my problem still persists…

**Comment by mrcoles** [comment]
Oh, I’m seeing the issue here. If you were doing it as a regex literal then you could write it as `/\w/`, but, since you’re passing a string into RegExp, you need to double-escape the "w" like this: `new RegExp('\\w')`.

```
> '\w' === 'w'
true
> '\\w' === 'w'
false
```

I do love regular expressions, but I am reminded of [this XKCD](https://xkcd.com/1171/). Relatedly, I’ve learned that any functions with regular expressions in them should pretty much always have associated unit tests, since they’re so easy to mess up.
